# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

homepage:
    path: /home
    controller: App\Controller\DefaultController::home
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'
mumbling:
  path: /mumbling/{characters}
  controller: App\Controller\MumblingController::MumblingDemo
  defaults:
    characters: 'Abcdef'
challenge_new:
  path: /api/v1/challenge/new
  controller: App\Controller\ChallengeController::new
challenge_show:
  path: /api/v1/challenge/show/{id}
  controller: App\Controller\ChallengeController::show    
buildtower_show:
  path: /api/v1/buildtower/show/{rows}
  controller: App\Controller\BuildTowerController::show 
  defaults:
    rows: 4
camelcase_show:
  path: /api/v1/camelcase/show/{strToCamelCase}
  controller: App\Controller\CamelCaseController::show 
  defaults:
    strToCamelCase: 'default string to camel case'    